### ISSUE TITLE
Back to CSS

### ISSUE THREAD

**Issue by nndda** [nndda/itchio-profile#3]
As much as I love SCSS, using this has really, _really_ slows down the development. Back then, the main reason I decided to use SCSS is to save tiny bits of characters due to SCSS' variable feature:
In CSS, the variable use would be something like:
```css
:root {
  --i: #fff;
}

.uwu {
  color: var(--i);
}
```
And using SCSS:
```scss
$epic-color: #fff;

.uwu {
  color: $epic-color;
}
```
Which then would compiles to:

```css
.uwu {
  color: #fff;
}
```
Saving lots of characters count. Also, I don't have worry about naming variables short, vague things like `--i`!

But, it slows down the development, as I can't just plops the CSS into the Firefox's Style Editor. But actually, Firefox does supports plopping SCSS to a site, and then editing it with `--watch`, but only on local stuff(?), or maybe I didn't set it up right, idk.

With the new CDN import hacks, I don't think I have to worry the character counts as much now.
